[build]
target = "x86_64-unknown-linux-gnu"
rustflags = [
    "-C", "target-cpu=native",
    "-C", "target-feature=+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+avx",
    "-C", "opt-level=3",
    "-C", "target-feature=+fast-math"
]
